### ISSUE TITLE
Deploy a new Tag / Release to let this library / project being used with PHP 8

### ISSUE THREAD

**Issue by itamair** [pschocke/google-maps-links#6]
Hi @pschocke thanks for all this ... 
BUT latest v1.0 release still has this requirement:

```
    "require": {
        "php": "^7.3"
    },
```

that was opportunely removed in this more recent commit: https://github.com/pschocke/google-maps-links/commit/55dae3f2380d209cfc0f81c4b522767669d816c6
so to make this nice library compatible with PHP 8+.

Though still a new Release should be deployed (asap) so to make this library compatible and requirable with composer and PHP 8+.

In this meanwhile I was forced to create my own Fork of this (to be able to use with PHP 8+):
https://github.com/itamair/google-maps-links
and parallel packagist: https://packagist.org/packages/itamair/google-maps-links

But I will be happy to remove those, once this one as soon as this becomes PHP 8+ compatible.

**Comment by pschocke** [comment]
Hey @itamair, thanks for pointing this out! I've now released a new version :)

Have a good new year!

**Comment by itamair** [comment]
Thanks @pschocke ... nice job. And Happy New 2025 to you too!
